from enum import StrEnum
from typing import Any


class ErrorCode(StrEnum):
    PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"
    PROJECT_PRODUCT_IMMUTABLE = "PROJECT_PRODUCT_IMMUTABLE"
    COPY_REVIEW_REQUIRED = "COPY_REVIEW_REQUIRED"
    BARCODE_TYPE_REQUIRED = "BARCODE_TYPE_REQUIRED"
    BARCODE_VALUE_INVALID = "BARCODE_VALUE_INVALID"
    BARCODE_LENGTH_INVALID = "BARCODE_LENGTH_INVALID"
    BARCODE_CHECK_DIGIT_INVALID = "BARCODE_CHECK_DIGIT_INVALID"
    BARCODE_NOT_CONFIRMED = "BARCODE_NOT_CONFIRMED"
    BARCODE_RENDER_FAILED = "BARCODE_RENDER_FAILED"
    BARCODE_DECODE_FAILED = "BARCODE_DECODE_FAILED"
    BARCODE_VALUE_MISMATCH = "BARCODE_VALUE_MISMATCH"
    OCR_TEXT_MISMATCH = "OCR_TEXT_MISMATCH"
    OUTPUT_SIZE_INVALID = "OUTPUT_SIZE_INVALID"
    PROVIDER_RATE_LIMITED = "PROVIDER_RATE_LIMITED"
    PROVIDER_CIRCUIT_OPEN = "PROVIDER_CIRCUIT_OPEN"
    JOB_ALREADY_RUNNING = "JOB_ALREADY_RUNNING"
    JOB_CANCELLED = "JOB_CANCELLED"
    QUALITY_REVIEW_REQUIRED = "QUALITY_REVIEW_REQUIRED"
    RESOURCE_ACCESS_DENIED = "RESOURCE_ACCESS_DENIED"


def error_payload(
    code: ErrorCode,
    message: str,
    *,
    request_id: str,
    details: dict[str, Any] | None = None,
) -> dict[str, Any]:
    return {
        "code": code.value,
        "message": message,
        "details": details or {},
        "request_id": request_id,
    }

